server:
  port: 6001 # 服务端口

eureka:
  instance:
    hostname: eureka6001.com # eureka服务端的实例名称
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl: #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://eureka6002.com:6002/eureka/

#  关闭Erueka自我保护机制
  server:
    enable-self-preservation: false